export default {
  URL_PARAM_IS_MISSING: 'URL_PARAM_IS_MISSING',

  VK_RESPONSE_HAVE_EMPTY_DATA: 'VK_RESPONSE_HAVE_EMPTY_DATA',
  VK_RESPONSE_HAVE_BROKEN_DATA_TYPE: 'VK_RESPONSE_HAVE_BROKEN_DATA_TYPE',
  VK_RESPONSE_HAVE_BROKEN_VALUE: 'VK_RESPONSE_HAVE_BROKEN_VALUE',
  VK_RESPONSE_HAVE_BROKEN_SHARE_COUNT_VALUE: 'VK_RESPONSE_HAVE_BROKEN_SHARE_COUNT_VALUE',

  FB_RESPONSE_HAVE_EMPTY_DATA: 'FB_RESPONSE_HAVE_BROKEN_DATA',
  FB_RESPONSE_HAVE_EMPTY_SHARE_COUNT: 'FB_RESPONSE_HAVE_BROKEN_SHARE_COUNT',
  FB_RESPONSE_HAVE_BROKEN_SHARE_COUNT_TYPE: 'FB_RESPONSE_HAVE_BROKEN_SHARE_COUNT_TYPE',
};
